# -*- coding: utf-8 -*-
"""Copie de python_graphics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iLfW44QTi8oTHOROToTjjjoHjB1CTnsQ
"""



import matplotlib.pyplot as plt # Import the matplotlib library and assign it to the alias 'plt'

# "Graphique en courbes" du type lignes brisées (Line Chart)
fig = plt.figure()
ax = fig.add_axes([0,0,2,1])

pièces = ['Ach.', 'Eq.', 'Vesp.', 'Paix.', 'Nub.', 'Av.', 'Lys.', 'Thesm.', 'Ran.', 'Eccl.', 'Plut.']
Pourcentagedemotsprononcés = [0, 0.2, 0.5, 0.2, 0.1, 0, 56, 49, 2, 46, 2]
plt.plot(pièces,Pourcentagedemotsprononcés)
plt.xlabel('Pièces')
plt.ylabel('Pourcentage de mots prononcés')
plt.title('Diagramme en courbes : Représentation en pourcentage du nombre du mots prononcés par les femmes libres chez Aristophane')
plt.show()


# Diagramme en secteurs / circulaire (Circle Graph)
fig = plt.figure()
ax = fig.add_axes([0,0,1,1])
ax.axis('equal')
chiffres = [12.7, 0.2, 4.2]
catégories = ['Femme libre', 'Femme esclave', 'autre']
ax.pie(chiffres, labels = catégories, autopct = '%1.1f%%')
plt.title('Diagramme en secteurs : Représentation en pourcentage du statut des femmes chez Aristophane')
plt.show()